=== dkwdp/architecture-blueprint/schemas/level_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "next_level": {
      "anyOf": [
        {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "levelId": {
                  "type": "string"
                },
                "mapId": {
                  "type": "string"
                },
                "serverUrl": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "required": [
                "levelId"
              ],
              "additionalProperties": false
            },
            {
              "type": "string"
            }
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "elements": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "video"
              },
              "url": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": [
              "type",
              "url"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "text"
              },
              "markdown": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "markdown"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "interactive"
              },
              "entrypoint": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "entrypoint"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "switch"
              },
              "next_level": {
                "anyOf": [
                  {
                    "anyOf": [
                      {
                        "type": "object",
                        "properties": {
                          "levelId": {
                            "type": "string"
                          },
                          "mapId": {
                            "type": "string"
                          },
                          "serverUrl": {
                            "type": "string",
                            "format": "uri"
                          }
                        },
                        "required": [
                          "levelId"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "string"
                      }
                    ]
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            },
            "required": [
              "type",
              "next_level"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "button"
              },
              "url": {
                "type": "string",
                "format": "uri"
              },
              "text": {
                "type": "string"
              },
              "target": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "url",
              "text"
            ],
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "required": [
    "id",
    "title",
    "next_level",
    "elements"
  ],
  "additionalProperties": false
}

=== dkwdp/architecture-blueprint/static/content/map01/levels/coordinate_systems/content.json
{
  "id": "coordinate_systems",
  "title": "Interaktives Tutorial zum Thema Koordinatensysteme",
  "next_level": null,
  "elements": [
    {
      "type": "interactive",
      "entrypoint": "main.js"
    },
    {
      "type": "button",
      "text": "Start",
      "url": "https://scratch.mit.edu/projects/editor"
    }
  ]
}
